services:
  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - app_network

  backend:
    build: ./backend
    restart: always
    env_file: .env
    depends_on:
      - postgres
      - redis
    networks:
      - app_network
    volumes:
      - audio_cache:/app/audio_cache
      - ./cookies.txt:/app/cookies.txt:ro

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/app:/app/app
    restart: always
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app_network

volumes:
  postgres_data:
  audio_cache:
  redis_data:

networks:
  app_network:
    driver: bridge