events {
  worker_connections 1024;
}

http {
  include mime.types;
  default_type application/octet-stream;

  upstream backend {
    server backend:3000;
  }

  server {
    listen 8443 ssl;
    ssl_certificate /etc/nginx/certs/server-cert.pem;
    ssl_certificate_key /etc/nginx/certs/server-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    server_name localhost;

    location /api/ {
      proxy_pass http://backend;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_http_version 1.1;
    }

    location /audio/ {
      alias /audio_cache/;
      add_header Accept-Ranges bytes;
    }

    location / {
      proxy_pass http://frontend:4200;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}